import Head from 'next/head';
import styled from '@emotion/styled';
import { css } from '@emotion/react';

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 css={bold}>Hello</h1>
    </Container>
  );
}

const Container = styled.div`
  background-color: pink;
`;

const bold = css`
  font-weight: bold;
`;
